### ISSUE TITLE
Do histogram of quote counts per passage

### ISSUE THREAD

**Issue by JonathanReeve** [lit-mod-viz/middlemarch-critical-histories#27]

**Comment by milanterlunen** [comment]
By passage do you mean paragraph? I think that would be very useful. Even if we're mainly focusing on Chapters 15 and 20, it'd be nice to say "Other highly-quoted paragraphs in the novel are..." (presumably from e.g. Prelude, Ch1, Finale).

**Comment by milanterlunen** [comment]
It occurs to me that we probably want the same trio of data as with our other studies:
- raw frequency of quotes
- raw frequency of total words quoted
- total length of paragraph (for normalization)

**Comment by JonathanReeve** [comment]
I honestly forget what this issue title meant. I do have a new histogram of quote lengths, but I have no idea what "passage" could have referred to. (I need to start writing better descriptions for these things.) I don't think we really need to get into analyses of the level of paragraphs (they were tracked in the now-closed issues #15 and #18), since we already have the annotated edition that tracks quoted passages, and discussing chapters, passages, _and_ paragraphs seems like a bit much.
