### ISSUE TITLE
Why is Chapter 44 not quoted at all? 

### ISSUE THREAD

**Issue by JonathanReeve** [lit-mod-viz/middlemarch-critical-histories#31]
It would be interesting to write a paragraph about this.

**Comment by jojokarlin** [comment]
This is fascinating. I may quote Chapter 44 in my seminar paper just to start recuperating it.

**Comment by JonathanReeve** [comment]
Great! Feel free to assign this one to yourself if you like. I imagine it would be about a paragraph or two. I just added [contribution instructions](https://github.com/xpmethod/middlemarch-critical-histories/blob/master/paper/README.md) to the paper directory, so you can add it to the paper, too, if you want.
