### ISSUE TITLE
Graphs we need, using definitive data

### ISSUE THREAD

**Issue by milanterlunen** [lit-mod-viz/middlemarch-critical-histories#37]
- The heat map with normalized number of words, synchronic
- The heat map with normalized number of words, diachronic

**Comment by JonathanReeve** [comment]
The charts in [the e3 analysis](https://github.com/lit-mod-viz/middlemarch-critical-histories/blob/master/e3/e3-analysis.ipynb) as it currently stands is based on wordcounts, so I think this fixes this issue, if I'm understanding this correctly.
