### ISSUE TITLE
Compile data for 3a-b) matches+word counts per chapter, raw data and normalised for chapter length

### ISSUE THREAD

**Issue by sceckert** [lit-mod-viz/middlemarch-critical-histories#60]

**Comment by JonathanReeve** [comment]
Quoted words per chapter: are here: https://github.com/lit-mod-viz/middlemarch-critical-histories/blob/master/papers/spring2017-middlemarch-paper/data/num-words-quoted-per-chapter.csv

Number of quoted words per chapter, adjusted by the total number of words per chapter: https://github.com/lit-mod-viz/middlemarch-critical-histories/blob/master/papers/spring2017-middlemarch-paper/data/num-words-quoted-adjusted-by-total-words-in-chap.csv

**Comment by JonathanReeve** [comment]
[Quotations per chapter](https://github.com/lit-mod-viz/middlemarch-critical-histories/blob/master/papers/spring2017-middlemarch-paper/data/num-quotations-per-chapter.csv)

**Comment by JonathanReeve** [comment]
Ok, I think I have all of these, now, in the jstor-analysis notebook, unless it's one of the above-linked CSVs. Feel free to reopen this issue if not.
