### ISSUE TITLE
What is the matched phrase in ['Living Terraces in Ethiopia', 'Konso Landscape, Culture and Development', 'Front Matter']

### ISSUE THREAD

**Issue by milanterlunen** [lit-mod-viz/middlemarch-critical-histories#72]
Item number: 1547
Character range in Middlemarch: [[560109, 560839]]
Author: ['ELIZABETH E. WATSON']

Found among titles not including "Eliot" or "Middlemarch". Confusing why JSTOR included it and also why the matcher found a match.

**Comment by JonathanReeve** [comment]
Here's that character range: 

> eminent philosopher among my friends, who can dignify even your ugly
> furniture by lifting it into the serene light of science, has shown me
> this pregnant little fact.  Your pier-glass or extensive surface of
> polished steel made to be rubbed by a housemaid, will be minutely and
> multitudinously scratched in all directions; but place now against it a
> lighted candle as a centre of illumination, and lo! the scratches will
> seem to arrange themselves in a fine series of concentric circles round
> that little sun.  It is demonstrable that the scratches are going
> everywhere impartially and it is only your candle which produces the
> flattering illusion of a concentric arrangement, its light falling with
> an exclusive optical selection

Produced with this command-line command: `python -c "print(open('middlemarch.txt').read()[560109:560839])"`
